generatorName: kotlin
library: jvm-retrofit2
packageName: com.mobilemoney.sdk
apiPackage: com.mobilemoney.sdk.api
modelPackage: com.mobilemoney.sdk.models
artifactId: mobile-money-sdk
artifactVersion: 1.0.0
enumPropertyNaming: original
modelPropertyNaming: camelCase
dateLibrary: java8
serializationLibrary: gson
useCoroutines: true
omitGradleWrapper: true
hideGenerationTimestamp: true
additionalProperties:
  useRxJava3: false
  useAndroidMavenGradlePlugin: true
  androidSupport: true
