[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = r.sub.role == "admin" || (r.sub.role == p.sub && (p.obj == "*" || r.obj.type == p.obj) && (p.act == "*" || regexMatch(r.act, p.act)) && (!r.obj.checkOwner || r.sub.id == r.obj.ownerUserId))
