[workspace]
resolver = "2"
members = ["batch_payout", "blacklist", "bridge", "dispute", "escrow", "fee_tier", "htlc", "quicklendx-contracts", "oracle", "proof_of_reserve", "rebalancer", "router", "timelock", "vault"]

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true

[workspace.lints.rust]
unused_variables = "warn"
