import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: "category",
      label: "Overview & Architecture",
      items: [
        "BRIDGE_DOCUMENTATION_INDEX",
        "ARCHITECTURE",
        "STELLAR_EVM_BRIDGE_ARCHITECTURE",
        "BRIDGE_PROVIDER_COMPARISON",
        "BRIDGE_RESEARCH_SUMMARY",
      ],
    },
    {
      type: "category",
      label: "Setup & Deployment",
      items: [
        "DOCKER_DEV",
        "2FA_SETUP",
        "SETUP_LOCKS",
        "BRIDGE_DEPLOYMENT_RUNBOOK",
        "S3_SETUP_GUIDE",
        "DATABASE_BACKUPS",
        "CENTRALIZED_CONFIG",
      ],
    },
    {
      type: "category",
      label: "API & Core Features",
      items: [
        "BRIDGE_API_EXAMPLES",
        "BRIDGE_IMPLEMENTATION_GUIDE",
        "JWT_AUTHENTICATION",
        "SSO_INTEGRATION",
        "SEP10_AUTHENTICATION",
        "SEP12_KYC_API",
        "KYC_INTEGRATION",
        "KYC_DOCUMENT_UPLOAD",
        "VAULTS_API",
        "SEP31_IMPLEMENTATION",
        "FEE_STRATEGY_ENGINE",
        "FEE_BUMPING_IMPLEMENTATION",
        "API_VERSIONING",
        "ADVANCED_REDIS_CACHING",
        "GRAPHQL",
        "RBAC",
        "REFERENCE_NUMBERS",
        "REQUEST_TIMEOUTS",
        "TIMEOUT_QUICK_START",
        "TRANSACTION_FILTERING",
      ],
    },
    {
      type: "category",
      label: "Compliance & Operations",
      items: [
        "FRAUD_RULES",
        "ZK_BALANCE_PROOFS_ARCHITECTURE",
        "ZK_BALANCE_PROOFS_RESEARCH",
        "PAGERDUTY_INTEGRATION",
        "LOW_LIQUIDITY_ALERT_SYSTEM",
        "observability",
        "metrics",
        "slow-query-logging",
        "ELK_STACK",
        "read-replica-routing",
        "QUEUE_SYSTEM",
        "SCHEDULED_JOBS",
        "DISTRIBUTED_LOCKS",
      ],
    },
    {
      type: "category",
      label: "Testing & CI/CD",
      items: [
        "PACT_CONTRACT_TESTING",
        "CICD_PIPELINE",
        "CODE_COVERAGE",
        "CODECOV_SETUP",
        "STALE_BRANCH_CLEANUP",
      ],
    },
    {
      type: "category",
      label: "Integrations",
      items: [
        "ORANGE_INTEGRATION",
        "MAKE_COM_WEBHOOK_SETUP",
        "ZAPIER_WEBHOOK_SETUP",
        "metabase",
        "MONTHLY_STATEMENTS",
        "ADVANCED_DISPUTE_RESOLUTION",
      ],
    },
  ],
};

export default sidebars;
